#serverless.yml
service: formsli

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  memorySize: 2048
  timeout: 30
  logRetentionInDays: 14
  tags:
    service: ${self:service}
    region: ${self:provider.region}
  functions:
    postconfirmation: ${self:service}-${self:provider.stage}-postconfirmation
    invite: ${self:service}-${self:provider.stage}-invite
  profile: fl-infrastructure
  environment:
    region        : ${self:provider.region}
    domain        : ${opt:domain, 'dev-app.forms.li'}
    protocol      : ${opt:protocol, 'http://'}
    urlPrefix     : ${opt:urlPrefix, '${self:provider.environment.protocol}${self:provider.environment.domain}'}
    environment   : ${self:provider.stage}
    serviceName   : ${self:service}
    databaseName  : ${self:service}
    userPoolId    : ${ssm:/${self:provider.stage}/formsli/cognito/userpool/id}
    userPoolArn   : ${ssm:/${self:provider.stage}/formsli/cognito/userpool/arn}
    dbClusterId   : ${ssm:/${self:provider.stage}/formsli/rds/id}
    dbClusterArn  : "arn:aws:rds:#{AWS::Region}:#{AWS::AccountId}:cluster:${self:provider.environment.dbClusterId}"
    dbClusterSecretArn: ${ssm:/${self:provider.stage}/formsli/rds/password/secret}
    s3_user_bucket: ${ssm:/${self:provider.stage}/formsli/s3/bucket/name}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - "arn:aws:secretsmanager:ap-northeast-1:286358943194:secret:/${self:provider.stage}/formsli/rds/*"
    - Effect: "Allow"
      Action:
        - "rds-data:InsertItems"
        - "rds-data:GetItems"
        - "rds-data:UpdateItems"
        - "rds-data:DeleteItems"
        - "rds-data:ExecuteSql"
        - "rds-data:BatchExecuteStatement"
        - "rds-data:BeginTransaction"
        - "rds-data:CommitTransaction"
        - "rds-data:ExecuteStatement"
        - "rds-data:RollbackTransaction"
      Resource:
        - "${self:provider.environment.dbClusterArn}"
        - "${self:provider.environment.dbClusterArn}:*"
    - Effect: Allow
      Action:
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminUpdateUserAttributes
        - cognito-idp:AdminRemoveUserFromGroup
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminCreateUser
      Resource: "${self:provider.environment.userPoolArn}"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "arn:aws:ses:us-east-1:*:*"

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin
  - '@anttiviljami/serverless-stack-output'
  - serverless-appsync-offline
  - serverless-offline

resources:
  - ${file(resources/iam.yml)}
  - ${file(resources/apig.auth.yml)}

custom:
  # Stack Output Plugin
  output:
    file: outputs/stack.${self:provider.stage}.json # toml, yaml, yml, and json format is available
  # Servlerless Webpack (for functions)
  packagePath: './package.json'
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    packager: 'npm'   # Packager that will be used to package your external modules
    includeModules:
      forceInclude:
        - source-map-support
  appSync:
    name:  formsli-api-${self:provider.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: "${self:provider.environment.userPoolId}"
    logConfig:
      loggingRoleArn: { Fn::GetAtt: [AppSyncCloudWatchRole, Arn] } # Where AppSyncLoggingServiceRole is a role with CloudWatch Logs write access
      level: ALL
    schema: schema.graphql
    dataSources:
      - type: RELATIONAL_DATABASE
        name: AppData
        description: RDS source for formsli
        config:
          # The identifier for RDSCluster. Where RDSCluster is the cluster defined in Resources
          dbClusterIdentifier: ${self:provider.environment.dbClusterId}
          # The RDSClusterSecret ARN. Where RDSClusterSecret is the cluster secret defined in Resources
          awsSecretStoreArn: ${self:provider.environment.dbClusterSecretArn}
          databaseName: ${self:service}
          serviceRoleArn: { Fn::GetAtt: [AppSyncRDSRole, Arn] }
          region: ${self:provider.region}
    mappingTemplatesLocation: src/mapping-templates
    mappingTemplates: ${file(serverless.appsync-mappings.yml)}
    functionConfigurations: ${file(serverless.appsync-functions.yml)}
    ## Add substitutions here to replace all hardcoded table/index names in mapping templates
    substitutions:

functions:
  postConfirmation:
    name: ${self:provider.functions.postconfirmation}
    handler: src/postconfirmation.handle
    events:
      - http:
          path: /postconfirm
          method: post
          cors: true
      - cognitoUserPool:
          pool: fl-${self:provider.stage}-userpool
          trigger: PostConfirmation
          existing: true
  signup:
    name: ${self:provider.functions.invite}
    handler: src/invite.handle
    events:
      - http:
          path: /invite
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: MyApiGatewayAuthorizer
            claims:
              - email
              - username
              - custom:tenantId
              - custom:group