Resources:
  MyApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 10
      IdentitySource: method.request.header.Authorization
      Name: MyCognitoAuthorizer
      RestApiId:
        Ref: ApiGatewayRestApi
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - {"Fn::Join": ["", ["arn:aws:cognito-idp:", "#{AWS::Region}", ":", "#{AWS::AccountId}", ":userpool/", Ref: CognitoUserPoolMyUserPool]]}

# Print out the Id of the Authorizer
Outputs:
  Region:
    Value: "#{AWS::Region}"
  AccountId:
    Value: "#{AWS::AccountId}"
  AuthorizerId:
    Value:
      Ref: MyApiGatewayAuthorizer
  DBClusterId:
    Value: ${self:provider.environment.dbClusterId}
  DBSecretARN:
    Value: ${self:provider.environment.dbClusterSecretArn}