Resources:
  MyApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 10
      IdentitySource: method.request.header.Authorization
      Name: MyCognitoAuthorizer
      RestApiId:
        Ref: ApiGatewayRestApi
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - "${self:provider.environment.userPoolArn}"
  PostConfirmationTriggerInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: PostConfirmationLambdaFunction
    Properties:
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: ${self:provider.environment.userPoolArn}
      FunctionName: ${self:provider.functions.postconfirmation}
  # Create the admin user for the pool
  CognitoUserPoolAdminUser:
    Type : AWS::Cognito::UserPoolUser
    Properties:
      Username: infrastructure.${self:provider.stage}@forms.li
      UserPoolId: "${self:provider.environment.userPoolId}"
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: infrastructure.${self:provider.stage}@forms.li
        - Name: given_name
          Value: ${self:provider.stage} Infrastructure
        - Name: family_name
          Value: Admin
        - Name: email_verified
          Value: True
        - Name: "custom:group"
          Value: Admin
        - Name: "custom:region"
          Value: ${self:provider.region}
        - Name: "custom:environment"
          Value: ${self:provider.stage}
# Print out the Id of the Authorizer
Outputs:
  Region:
    Value: "#{AWS::Region}"
  AccountId:
    Value: "#{AWS::AccountId}"
  AuthorizerId:
    Value:
      Ref: MyApiGatewayAuthorizer
  DBClusterId:
    Value: ${self:provider.environment.dbClusterId}
  DBClusterArn:
    Value: "arn:aws:rds:#{AWS::Region}:#{AWS::AccountId}:cluster:${self:provider.environment.dbClusterId}"
  DBSecretARN:
    Value: ${self:provider.environment.dbClusterSecretArn}
  UserPoolId:
    Value: ${self:provider.environment.userPoolId}
  IdentityPoolId:
    Value: ${ssm:/dev/formsli/cognito/identitypool/id}
  UserPoolClientId:
    Value: ${ssm:/dev/formsli/cognito/userpool/clientId}
  UserPoolAdminUser:
    Value:
      Ref: CognitoUserPoolAdminUser