Resources:
  CognitoUserPoolMyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:provider.environment.serviceName}-userpool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailVerificationSubject: "Your Forms.li verification code"
      EmailVerificationMessage: "{####}"
      EmailConfiguration:
        SourceArn: "arn:aws:ses:us-east-1:#{AWS::AccountId}:identity/no-reply@forms.li"
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "tenant"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "environment"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "stack"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "region"
          Required: False
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:provider.environment.serviceName}-userpoolclient
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  CognitoAppAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Application Admin
      GroupName: Admin
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account admin
      GroupName: AccountAdmin
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountEditorGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account editor user
      GroupName: Editor
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountViewerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account read only user
      GroupName: Viewer
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPoolMyUserPool
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient