Resources:
  CognitoUserPoolMyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:provider.environment.serviceName}-userpool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:provider.environment.serviceName}-userpoolclient
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  CognitoAppAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Application Admin
      GroupName: Admin
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account admin
      GroupName: AccountAdmin
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountEditorGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account editor user
      GroupName: Editor
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountViewerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account read only user
      GroupName: Viewer
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  # UserPoolPostConfirmationLambdaInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:invokeFunction
  #     Principal: cognito-idp.amazonaws.com
  #     FunctionName: arn:aws:lambda:${self:provider.region}:${self:provider.accountId}:function:${self:provider.functions.postconfirmation}
  #     SourceArn: {"Fn::GetAtt": [ CognitoUserPool, Arn ]}
# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPoolMyUserPool
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient