Resources:
  CognitoUserPoolMyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:provider.stage}-${self:service}
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailVerificationSubject: "Your Forms.li verification code"
      EmailVerificationMessage: "{####}"
      EmailConfiguration:
        SourceArn: "arn:aws:ses:us-east-1:#{AWS::AccountId}:identity/no-reply@forms.li"
      AdminCreateUserConfig:
        InviteMessageTemplate:
          EmailSubject: "Welcome to Forms.li"
          EmailMessage: "Your username is {username} and temporary password is {####}"
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "tenantId"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "tenantName"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "source"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "group"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "environment"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "stack"
          Required: False
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "region"
          Required: False

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:provider.environment.serviceName}-userpoolclient
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      GenerateSecret: false
      ReadAttributes:
        - email
        - given_name
        - family_name
        - website
        - email_verified
        - email
        - profile
        - phone_number
        - phone_number_verified
        - "custom:tenantId"
        - "custom:tenantName"
        - "custom:source"
        - "custom:environment"
        - "custom:stack"
        - "custom:region"
        - "custom:group"
      WriteAttributes:
        - email
        - given_name
        - family_name
        - phone_number
        - address
        - website
        - profile
        - locale
        - "custom:group"
        - "custom:tenantName"
        - "custom:source"
  CognitoUserPoolAdminClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:provider.environment.serviceName}-userpooladminclient
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
      ReadAttributes:
        - email
        - given_name
        - family_name
        - website
        - email_verified
        - email
        - profile
        - phone_number
        - phone_number_verified
        - "custom:tenantId"
        - "custom:tenantName"
        - "custom:source"
        - "custom:group"
        - "custom:environment"
        - "custom:stack"
        - "custom:region"
      WriteAttributes:
        - "custom:tenantId"
        - "custom:tenantName"
        - "custom:source"
        - "custom:environment"
        - "custom:stack"
        - "custom:region"
        - "custom:group"
  CognitoAppAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Application Admin
      GroupName: Admin
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account admin
      GroupName: AccountAdmin
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountEditorGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account editor user
      GroupName: Editor
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  CognitoAccountViewerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Account read only user
      GroupName: Viewer
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
  # Create the admin user for the pool
  CognitoUserPoolAdminUser:
    Type : AWS::Cognito::UserPoolUser
    Properties:
      Username: infrastructure.${self:provider.stage}@forms.li
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: infrastructure.${self:provider.stage}@forms.li
        - Name: given_name
          Value: ${self:provider.stage} Infrastructure
        - Name: family_name
          Value: Admin
        - Name: email_verified
          Value: True
        - Name: "custom:group"
          Value: Admin
        - Name: "custom:region"
          Value: ${self:provider.region}
        - Name: "custom:environment"
          Value: ${self:provider.stage}
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPoolMyUserPool
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
  AdminUserPoolClientId:
    Value:
      Ref: CognitoUserPoolAdminClient
  UserPoolAdminUser:
    Value:
      Ref: CognitoUserPoolAdminUser