Resources:
  AppDataTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
          TableName: ${self:provider.environment.table_app_data}
          StreamSpecification:
            StreamViewType: NEW_AND_OLD_IMAGES
          AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: itemType
                AttributeType: S
              - AttributeName: meta
                AttributeType: S
              - AttributeName: createdAt
                AttributeType: S
              - AttributeName: owner
                AttributeType: S
          KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: itemType
                KeyType: RANGE
          ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          GlobalSecondaryIndexes:
              - IndexName: ${self:provider.environment.table_app_data}_gsi_meta
                KeySchema:
                  - AttributeName: itemType
                    KeyType: HASH
                  - AttributeName: meta
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: 5
                  WriteCapacityUnits: 5
              - IndexName: ${self:provider.environment.table_app_data}_gsi_created
                KeySchema:
                  - AttributeName: itemType
                    KeyType: HASH
                  - AttributeName: createdAt
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: 5
                  WriteCapacityUnits: 5
              - IndexName: ${self:provider.environment.table_app_data}_gsi_owner
                KeySchema:
                  - AttributeName: itemType
                    KeyType: HASH
                  - AttributeName: owner
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: 5
                  WriteCapacityUnits: 5
  FormEntriesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
          TableName: ${self:provider.environment.table_form_entries}
          StreamSpecification:
            StreamViewType: NEW_IMAGE
          AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: formId
                AttributeType: S
              - AttributeName: createdAt
                AttributeType: S
          KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: formId
                KeyType: RANGE
          ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          GlobalSecondaryIndexes:
              - IndexName: ${self:provider.environment.table_form_entries}_gsi_created
                KeySchema:
                  - AttributeName: formId
                    KeyType: HASH
                  - AttributeName: createdAt
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: 5
                  WriteCapacityUnits: 5

# Print out the name of the FormEntriesTable
Outputs:
  FormEntriesTable:
    Value:
      Ref: FormEntriesTable
  FormEntriesGSI:
    Value: ${self:provider.environment.table_form_entries}_gsi
# Print out the name of the AppDataTable
  AppDataTable:
    Value:
      Ref: AppDataTable
  AppDataGSI:
    Value: ${self:provider.environment.table_app_data}_gsi