Resources:
  AppDataTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
          TableName: ${self:provider.environment.table_app_data}
          AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: type
                AttributeType: S
              - AttributeName: meta
                AttributeType: S
          KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: type
                KeyType: RANGE
          ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          GlobalSecondaryIndexes:
              - IndexName: ${self:provider.environment.table_app_data}_gsi
                KeySchema:
                  - AttributeName: type
                    KeyType: HASH
                  - AttributeName: meta
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: 5
                  WriteCapacityUnits: 5
  FormEntriesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
          TableName: ${self:provider.environment.table_form_entries}
          AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: type
                AttributeType: S
              - AttributeName: meta
                AttributeType: S
          KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: type
                KeyType: RANGE
          ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          GlobalSecondaryIndexes:
              - IndexName: ${self:provider.environment.table_form_entries}_gsi
                KeySchema:
                  - AttributeName: type
                    KeyType: HASH
                  - AttributeName: meta
                    KeyType: RANGE
                Projection:
                  ProjectionType: ALL
                ProvisionedThroughput:
                  ReadCapacityUnits: 5
                  WriteCapacityUnits: 5
# Print out the name of the FormEntriesTable
Outputs:
  FormEntriesTable:
    Value:
      Ref: FormEntriesTable
# Print out the name of the AppDataTable
  AppDataTable:
    Value:
      Ref: AppDataTable