Resources:
  AppSyncRDSRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "${self:service}-${self:provider.region}-appsync-iam-role"
      ManagedPolicyArns:
        - Ref: AppSyncRDSPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "appsync.amazonaws.com"
    DependsOn:
      - AppSyncRDSPolicy
  AppSyncRDSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow AWS AppSync to access RDS.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "rds-data:InsertItems"
              - "rds-data:GetItems"
              - "rds-data:UpdateItems"
              - "rds-data:DeleteItems"
              - "rds-data:ExecuteSql"
              - "rds-data:BatchExecuteStatement"
              - "rds-data:BeginTransaction"
              - "rds-data:CommitTransaction"
              - "rds-data:ExecuteStatement"
              - "rds-data:RollbackTransaction"
              - "tag:GetResources"
            Resource:
              - "${self:provider.environment.dbClusterArn}"
              - "${self:provider.environment.dbClusterArn}:*"
          - Effect: "Allow"
            Action:
              - "secretsmanager:GetSecretValue"
              - "secretsmanager:CreateSecret"
              - "secretsmanager:ListSecrets"
              - "secretsmanager:GetRandomPassword"
            Resource:
              - "arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:/${self:provider.stage}/formsli/rds/*"
          - Effect: "Allow"
            Action:
              "tag:GetResources"
            Resource:
              - "*"
  AppSyncCloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "${self:service}-${self:provider.region}-appsync-logging-iam-role"
      ManagedPolicyArns:
        - Ref: AppSyncCloudWatchPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "appsync.amazonaws.com"
    DependsOn:
      - AppSyncCloudWatchPolicy
  AppSyncCloudWatchPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow AWS AppSync to write logs
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
  KinesisAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow AWS AppSync to write logs
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:AbortMultipartUpload"
              - "s3:GetBucketLocation"
              - "s3:GetObject"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:PutObject"
            Resource:
              Fn::Join:
                - ":"
                - 
                  - "arn"
                  - Ref: 'AWS::Partition'
                  - "s3::"
                  - ${self:provider.environment.s3_user_bucket}*
          - Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Resource: "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/*"
            Condition:
              StringEquals:
                "kms:ViaService" : "s3.#{AWS::Region}.amazonaws.com"
              StringLike:
                "kms:EncryptionContext:aws:s3:arn" : "arn:aws:s3:::${self:provider.environment.s3_user_bucket}/home*"
          - Effect: "Allow"
            Action:
              - "logs:PutLogEvents"
            Resource:
              - "arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:*:*:*:*"
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
              - "lambda:GetFunctionConfiguration"
            Resource:
              - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:*:*"
  KinesisAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "${self:service}-${self:provider.region}-kinesis-iam-role"
      ManagedPolicyArns:
        - Ref: KinesisAccessPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Condition:
              StringEquals:
                "sts:ExternalId": "#{AWS::AccountId}"
    DependsOn:
      - KinesisAccessPolicy
Outputs:
  Region:
    Value: ${self:provider.region}
  Stage:
    Value: ${self:provider.stage}
  Service:
    Value: ${self:service}