Resources:
  AppsyncCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - GraphQlApi
    Properties:
      Tags:
        Key: Name
        Value: ${self:provider.namePrefix}cf-graphql
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName:
            !Select [2, !Split ['/', !GetAtt 'GraphQlApi.GraphQLUrl']]
          Id: { Fn::GetAtt: [GraphQlApi, ApiId] }
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginKeepaliveTimeout: 300
            OriginReadTimeout: 60
            OriginProtocolPolicy: https-only
            OriginSSLProtocols: [ TLSv1.2 ]
        Aliases:
          - ${self:provider.environment.gqlDomain}
        DefaultCacheBehavior:
          AllowedMethods: [ HEAD, DELETE, POST, GET, OPTIONS, PUT, PATCH ]
          ForwardedValues:
            QueryString: false
            Headers:
              - Authorization
          SmoothStreaming: false
          Compress: true
          TargetOriginId: { Fn::GetAtt: [GraphQlApi, ApiId] }
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
          AcmCertificateArn: ${self:provider.environment.usEastCertArn}