Resources:
  AppsyncDnsRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: ${self:provider.environment.hostedZoneId}
      RecordSets:
        - Name: ${self:provider.environment.gqlDomain}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: { Fn::GetAtt: [AppsyncCloudfrontDistribution, DomainName] }